apiVersion: v2
name: webrix-helm
description: A unified Helm chart for deploying all Webrix services (app, connect, run, db-service)
type: application
version: 1.0.0

dependencies:
  - name: postgresql
    version: "16.7.12"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
