{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
    app: {{ $serviceName }}
data:
  {{- range $key, $value := $serviceConfig.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := $.Values.sharedEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := $serviceConfig.extraEnv }}
  {{- if and (eq $key "DATABASE_URL") (eq $serviceName "dbService") }}
  {{ $key }}: {{ include "webrix.databaseUrl" $ | quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  CONNECT_URL: "https://connect.{{ $.Values.global.domain.host }}"
  RUN_URL: "https://run.{{ $.Values.global.domain.host }}"
  DB_SERVICE_URL: "https://dbservice.{{ $.Values.global.domain.host }}"
  BASE_URL: "https://{{ $serviceName | lower }}.{{ $.Values.global.domain.host }}"
  NEXTAUTH_URL: "https://{{ $serviceName | lower }}.{{ $.Values.global.domain.host }}"
  DB_BASE_URL: "https://dbservice.{{ $.Values.global.domain.host }}"
  NEXT_PUBLIC_CONNECT_URL: "https://connect.{{ $.Values.global.domain.host }}"
{{- end }}
{{- end }}
