{{- range $name, $deployment := .Values.deployments }}
{{- if $deployment.sealedsecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := $deployment.sealedsecret }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "webrix.labels" $ | nindent 8 }}
{{- end }}
{{- end }}
