{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
type: Opaque
data: {}
{{- end }}
{{- end }}
