{{- range $serviceName, $serviceConfig := .Values.deployments }}
{{- if and $serviceConfig.enabled $serviceConfig.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-sa" $serviceName | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "webrix.labels" $ | nindent 4 }}
    app: {{ $serviceName }}
  {{- with $serviceConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
